
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int UMINUS = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int SEMICOLON = 8;
  public static final int RPAREN = 6;
  public static final int TIMES = 4;
  public static final int RETURN = 7;
  public static final int INTCONST = 10;
  public static final int LPAREN = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "RETURN",
  "SEMICOLON",
  "UMINUS",
  "INTCONST"
  };
}

